= HpsCheck
:toc:
:toc-title: 목차

== 1. HpsCheck 개요

HpsCheck는 HyperSQL PS팀이 PostgreSQL 기술지원 시 고객 지원에 필요한 컨텐츠를 담아놓은 쉘 스크립트입니다. 
PS 팀 누구나 참여하여 더 좋은 컨텐츠를 담을 수 있게 끔 아래 항목에 내용을 정리하니, 참고하셔서 내용 수정 및 더 좋은 아이디어/컨텐츠 공유 부탁드립니다.

현재는 아래와 같이 구성되어 있습니다.

- hpscheck.sh : 기술지원 쉘 스크립트로, 내부에서 sql 폴더 내의 각 항목에 맞는 sql 구문을 실행합니다.
- sql : 기술지원 쉘 스크립트에 기재된 항목에 맞는 sql 구문들이 각각 .sql 파일형태로 저장되어있습니다.
- chkreslt : 기술지원 쉘 스크립트 옵션 중, file write 옵션이 true 일 경우, 각 데이터베이스 명의 하위 디렉토리가 생성되며, 하위 디렉토리 내부에 쉘스크립트 항목별로 텍스트 파일이 생성됩니다.


== 2. hpscheck.sh 쉘 스크립트 항목 별 내용

- 쉘 스크립트 동작 방식 개요

* 쉘 실행 예시
[source,sh]
----

-bash-4.2$ ./hpscheck.sh

##### Start HyperSQL PostgreSql Check Program #####

Input Database Name :
testdb

##### Database Checked #####


Input Owner Name :
tester

##### Owner Checked #####


Input Owner Password :

##### Password Checked #####

##### Write Result Files? (y/n) ##### input : n
##### File Write Mode Off #####

##### CURRENT DATABASE is testdb #####
##### CURRENT OWNER is tester #####
##### File Write Off #####

##### SELECT CONTENTS #####
0. Version Check
1. Database & Owner Check
2. Conf Check
3. Memory Check
4. Process Check
5. Space Usage Check
6. System Resource and FileSystem Check
7. Disk I/O Check
8. Current Session Check
9. Top 10 Sql Check
10. Vacuum Check
11. Log Check
12. Lock Check
\c. Change Database & Owner
\f. Change File Write mode(flag : n)
\q. Exit Program
#############################
input number :
----


쉘을 실행하게되면, 데이터베이스명, 소유자, 패스워드, 파일 write 여부 체크 순으로 입력하게 됩니다.

정확하게 순서대로 입력하게 되면 체크 할 수 있는 컨텐츠들이 보이며, input number 부분에 항목의 숫자를 입력하고 엔터를 누르면 해당 항목의 내용이 보여지게 됩니다. 항목은 case 문으로 구현되었습니다.

항목 들어갈 때마다 화면 클리어링을 시작함과 동시에 파일 write 여부 설정한 것에 따라 파일을 생성하거나 결과만 출력하게 되며, 항목 내 세부 내용은 엔터를 눌러야 다음 내용을 볼 수 있습니다.

파일은 각 항목 맨 처음에 해당 항목의 파일을 지우는 것으로 시작합니다(항목 다시 시작으로 인해 복잡한 append를 피하기 위함). ">" 명령어를 통해 각 항목의 맨 처음 내용을 기록하며 항목이 끝날 때까지 이어진 내용은 ">>" 명령어를 통해 append 되도록 구현했습니다.

한 항목의 내용을 다 보게되면 컨텐츠 내용이 다시 나오게되는 무한 루프식으로 되어있으며, 내용을 다 체크했다면 "\q" 입력으로 쉘을 빠져 나올 수 있습니다(강제종료도 가능합니다).

파일 저장을 활성화 했다면 chkreslt 디렉토리 내에 데이터베이스명 하위 디렉토리가 생성되며, 아래에 본 항목이 항목명.txt 파일 형태로 생성되어있습니다. 

파일 저장 활성화는 쉘스크립트 실행 도중 끄거나 재활성화 할 수 있도록 /f 항목으로 빼놨습니다.

아래는 각 항목별 쉘 스크립트 내 세부 설명입니다.

=== 2.1. 스크립트 실행시 나오는 항목

- Input Database Name +
점검하고자하는 database 명을 넣으며, 입력 값을 dbcheck.sql에 인자값으로 전달하여 database명이 틀릴 경우 다시 입력하라는 메시지를 띄우며 정확하게 작성 될 때까지 무한 반복됩니다.


- Input Owner Name +
점검하고자 하는 소유자 명을 넣으며, 입력 값을 usercheck.sql에 인자값으로 전달하여 소유자명이 틀릴 경우 다시 입력하라는 메시지를 띄우며 정확하게 작성 될 때까지 무한 반복됩니다.


- Input Owner Password +
소유자의 패스워드를 넣으며, 해당 패스워드로 접속을 해서 select version() 쿼리를 실행합니다. 결과값이 나오면 패스워드 입력이 성공, 안나오면 틀리다고 판정하여 패스워드가 틀릴 경우 다시 입력하라는 메시지를 띄우며 정확하게 작성 될 때까지 무한 반복됩니다.

- Write Result Files? (y/n) input : +
파일을 chkreslt 폴더 내에 위 database name에서 입력한 db명으로 하위디렉토리 생성하여 작성할지 안할지를 y또는 n을 입력해서 flag 값을 y또는 n으로 설정합니다. 파일 write 부분은  if ~ else 구문에서 파일을 쓸 때, 안쓸 때 분기구분하도록 되어있는데 flag 값은 이때 사용됩니다.

전부 입력하게 되면 현재 DB, 소유자, 파일 write mode 여부와 함께 점검 항목을 보여줍니다.

그리고 DB명, 소유자명, 패스워드를 체크하는 것은 전부 기본 DB와 소유자인 postgres 를 통해 진행하며, postgres는 쉘 스크립트에 하드코딩 되어있습니다. 만약 postgres 소유자의 패스워드가 다르게 설정되어있다면, hpscheck.sh 쉘 내부에서 패스워드 설정 해준 뒤 실행해야합니다.
[source,sh]
----
defdb="postgres"
defown="postgres"
defpwd="postgres" <- 수정 필요
----

=== 2.2. Version Check

0_version.sql 구문을 실행하는 부분이며 현재 PostgreSQL의 버전을 보여주는 항목입니다. 파일을 쓰게 되면 0_version.txt 파일명으로 남기게 됩니다.

=== 2.3. Database & Owner Check

1_dblist.sql 구문을 실행하는 부분이며 데이터베이스 목록과 소유자 목록을 보여주는 항목입니다. 파일을 쓰게되면 1_dbownerchk.txt 파일명으로 남기게 됩니다.

=== 2.4. Conf Check

2_archchk.sql, 2_pghback.sql, 2_vacuumchk.sql, 2_walchk.sql 구문들을 실행하는 부분이며 postgresql.conf에서 archive 세팅목록, vacuum 세팅목록, wal 세팅목록을, pg_hba.conf에서 접근제어 설정이 어떻게 되어있는지 query 결과로 보여주는 항목입니다. 파일을 쓰게되면 2_confchk.txt 파일명으로 남기게 됩니다.

=== 2.5. Memory Check

3_processmemory.sql, 3_sharedmemory.sql 구문들을 실행하는 부분이며 postgresql.conf에 설정된 메모리 값을 보여주고, CLOG buffer 값도 계산하여 볼 수 있습니다. vacuum 버퍼 값 계산은 스터디 후에 수정여지가 있다면 진행해야합니다. 파일을 쓰게되면 3_memchk.txt 파일명으로 남기게 됩니다.

=== 2.6. Process Check

따로 sql 구문을 활용하지 않으며 프로세스를 확인할 수 있는 ps -ef 명령어로 현재 postgresql의 프로세스를 보여줍니다. 필요없는 부분은 grep 구문으로 자르고 보여주도록 되어있으며 현재 아래와 같이 설정했습니다.
[source,sh]
----
ps -ef |grep postgres | awk '$1 ~ /^postgres$/ {print}' | grep -v  grep | grep -v bash | grep -v ps | grep -v idle | grep -v awk
----

추후 postgresql을 실행하는 유저명이 다를경우, 추가되는 extension 체크를 위해 수정할 여지가 있습니다. 파일ㅇ르 쓰게되면 4_processchk.txt 파일명으로 남기게 됩니다.

=== 2.7. Space Usage Check

5_dbsize.sql, 5_tbixsize.sql, 5_tbssize.sql 구문을 실행하는 부분이며, 물리적인 디스크 용량을 확인 하기 위해 쉘 명령어도 포함됩니다. 쉘 명령어는 df -h와 du -sh가 사용되며, $PGDATA경로의 물리적인 용량을 체크합니다. 그러면서 쉘에 입력하고 들어온 데이터베이스의 사이즈와 쉘에 입력하고 들어온 소유자가 가진 테이블 스페이스 사이즈를 확인합니다. 그리고 데이터베이스가 가지고있는 테이블들과 인덱스, 그리고 total relation 사이즈를 볼 수 있습니다. 파일을 쓰게되면 5_spaceusage.txt 파일명으로 남기게 됩니다.

=== 2.8. System Resource and FileSystem Check

따로 sql 구문을 활용하지 않으며 현 서버의 리소스와 cpu, 메모리 사용량을 vmstat으로 보여줍니다. 그리고 postgresql 파일 시스템들의 디렉토리 내용을 보여줍니다. 이부분은 vmstat 및 top에 관련된 세미나 이후 수정될 여지가 있으며, 파일 시스템들의 디렉토리 내용을 보여주기보다 디렉토리 경로를 보여주는 방식으로 수정 될 예정입니다. 파일을 쓰게되면 6_resourcechk.txt 파일명으로 남기게 됩니다.

=== 2.9. Disk I/O Check

7_diskio.sql 구문을 실행하는 부분이며 데이터베이스(buffercache) I/O 및 hit ratio, 테이블 I/O 및 hit ratio, 인덱스 I/O 및 hit ratio, 시퀀스 I/O 및 hit ratio, SLRU(simple least-recently_used) I/O 및 hit ratio를 볼 수 있습니다. 등급은 90% 이상이면 good, 미만이면 bad, read와 hit 값이 없으면 not work로 구분됩니다. 등급은 내부 기준을 만들어서 세분화가 필요합니다. 파일을 쓰게되면 7_diskiochk.txt 파일명으로 남기게 됩니다.

=== 2.10. Current Session Check

8_sessioncheck.sql, 8_transactionchk.sql 구문들을 실행하는 부분이며 현재 세션과 트랜잭션을 볼 수 있습니다. 파일을 쓰게 되면 8_cursessionchk.txt 파일명으로 남기게 됩니다.

=== 2.11. Top 10 Sql Check

9_sqlplan.sql, 9_topsqlchk.sql 구문들을 실행하는 부분이며 실행시간이 제일 많은 10가지 query를 볼 수 있습니다. 그 query에 관련된 plan을 explain verbose 구문을 사용하여 보여주려 했으나, select 이외의 구문이 실행되면 운영에 크리티컬 하기 때문에 전면 수정했으며, 쿼리의 plan정보를 볼 수 있는 시스템 카탈로그를 찾고 공부하여 추가해야합니다. 또한 query는 query id값만 보여주도록하여 좀 더 보기 편하게 수정할 계획입니다. 파일을 쓰게되면 9_topsqlchk.tx 파일명으로 남기게 됩니다.

=== 2.12. Vacuum Check

10_tableusage.sql, 10_tuplestate.sql, 10_vacuumcheck.sql, 10_vacuumstate.sql 구문들을 실행하는 부분이며 live tuple, dead tuple과 live tuple의 비율을 볼수 있고, 테이블 사이즈와 vacuum과 analyze가 실행되었던 기록을 볼 수 있습니다. vacuum이 postgresql에서 중요한 부분이므로 스터디를 통해 내용을 보완해야 합니다. 파일을 쓰게되면 10_vacuumchk.txt 파일명으로 남기게 됩니다.

=== 2.13. Log Check

따로 sql 구문을 활용하지 않으며 $PGDATA의 log 디렉토리에 쌓인 로그들과, 오류 내용을 grep 해서 볼 수 있습니다. 로그 정책을 수립하게되면 수정할 부분입니다. 파일을 쓰게되면 11_logchk.txt 파일명으로 남기게 됩니다.

=== 2.14. Lock Check

12_check_lock.sql 구문을 실행하는 부분이며 현재 lock 관련된 부분을 확인 할 수 있고, block된 lock도 볼 수 있습니다. lock 관련 부분도 모든 DB에서 중요한 만큼 더 스터디하여 내용을 보충해야합니다. 파일을 쓰게되면 12_lockchk.txt 파일명으로 남기게 됩니다.

=== 2.15. 기타

항목 중 숫자가아닌 \c, \f, \q 부분 관련입니다. +

\c는 check shell 을 빠져나가지 않고 실행하는 도중에 데이터베이스와 소유자를 변경할 수 있는 항목입니다. 로직은 처음에 실행되는 부분과 똑같이 입력하도록 되어있습니다.

\f는 파일을 write 여부를 바꿀 수 있는 부분이며, 마찬가지로 check shell을 빠져나가지 않고 실행하는 도중에 바꿀 수 있습니다. 다른 입력값 없이 /f 누르면 바로 write 모드가 바뀌게 되며, 바뀐 여부도 같이 출력됩니다.

\q는 실행도중 빠져나갈수 있는 값으로, 강제종료 외에 \q 외에 다른 입력값을 넣게되면 잘못된 입력값이라는 문구와 함께 계속 루프를 돌게 됩니다.


== 3. sql 폴더 내 각 sql 파일 내부 설명

- dbcheck.sql
[source,sql]
----
select
        coalesce(max(datname),'0')
from
        pg_stat_database
where
        datname = :v1;
----

:v1 부분에서 쉘에서 입력받은 database 명이 들어가게되며, coalesce 함수와 max 함수가 사용됩니다. colaesce 함수를 사용하는 이유는, 쿼리 결과값이 null이 나오게되면 null값 대신 0으로 값을 대체해, 이를 쉘스크립트에 전달하여 database 명이 존재하는지 안하는지 로직에 반영하게 됩니다. max를 사용한 이유는, max를 사용하지 않을 경우 null일 때 0 값이 출력되지 않아 구글링을 통해 max를 같이 사용해야한다는 커뮤니티의 글을 보고 반영했습니다.

- usercheck.sql
[source,sql]
----
select
        coalesce(max(usename),'0')
from
        pg_shadow
where
        usename = :v1;
----

pg_shadow 뷰를 이용하여 :v1 부분에서 쉘에서 입력받은 소유자 명이 들어가게 되며, coalesce 함수와 max 함수가 사용됩니다.

- 0_version.sql
[source,sql]
----
select version();
----

단순 버전을 확인 할 수 있는 쿼리입니다.

- 1_dblist.sql
[source,sql]
----
select
        s.usename as owner,
        d.datname as database_name,
        pg_encoding_to_char(d.encoding) as encoding, --encoding id값을 char로 변환
        d.datcollate as colate,
        d.datctype as ctype,
        d.datacl as acl_auth --접근 권한 
from
        pg_database d, pg_shadow s
where
        s.usesysid = d.datdba;


select
        usename as owner_list
from
        pg_shadow;

----

현재 존재하는 데이터베이스와 소유주들을 모두 볼 수 있고, 각 encoding 값과 접근 권한까지 볼 수 있는 쿼리 입니다.

- 2_archchk.sql
[source,sql]
----
select
        name,
        setting,
        category
from
        pg_settings
where
        name like 'archive%';
----

where 조건에 archive를 따로 명시해 해당 값만 볼 수 있습니다. pg_settings 테이블의 다른 컬럼 내용중, min max 설정도 같이 볼 수 있는 부분과 다른 컬럼들도 있는데, 엔지니어에 필요한 부분 추가 예정입니다.

- 2_pghbachk.sql
[source,sql]
----
select
        type,
        database,
        user_name,
        address,
        auth_method
from
        pg_hba_file_rules;
----

pg_hba.conf 파일 내용이 담겨있는 테이블로 조회한 내용입니다.


- 2_vacuumchk.sql
[source,sql]
----
select
name,
setting,
category
from pg_settings
where name like '%vacuum%';
----
where 조건에 vacuum을 따로 명시해 해당 값만 볼 수 있습니다. pg_settings 테이블의 다른 컬럼 내용중, min max 설정도 같이 볼 수 있는 부분과 다른 컬럼들도 있는데, 엔지니어에 필요한 부분 추가 예정입니다.


- 2_walchk.sql
[source,sql]
----
select
        name,
        setting,
        category
from
        pg_settings
where
        name like '%wal%';
----

where 조건에 wal를 따로 명시해 해당 값만 볼 수 있습니다. pg_settings 테이블의 다른 컬럼 내용중, min max 설정도 같이 볼 수 있는 부분과 다른 컬럼들도 있는데, 엔지니어에 필요한 부분 추가 예정입니다.

- 3_processmemory.sql
[source,sql]
----
select
        a.setting as autovacuum_work_mem,
        c.setting as autovacuum_max_workers,
        case when cast(a.setting as integer) = -1 then pg_size_pretty(cast(b.setting as bigint)*1024*cast(c.setting as integer))
             when cast(a.setting as integer) > 0 then pg_size_pretty(cast(a.setting as bigint)*1024*cast(c.setting as integer))
             when pg_size_pretty(cast(a.setting as bigint)*1024*cast(c.setting as integer)) > pg_size_pretty(1024*1024*1024::bigint) then pg_size_pretty(1024*1024*1024::bigint)
        end as vaccum_buffer
from
        pg_settings a, pg_settings b , pg_settings c
where
        a.name = 'autovacuum_work_mem' and b.name = 'maintenance_work_mem' and c.name='autovacuum_max_workers';

show work_mem;

show maintenance_work_mem;

show temp_buffers;
----

work_mem, maintenance_work_mem, temp_buffers 세팅된 값을 확인할 수 있으며 추가로 vacuum buffer 값 계산을 넣었는데, vacuum buffer는 autovacuum_work_mem, autovacuum_max_workers 부분만 볼 수 있게 하고 계산 값은 커뮤니티에서 토론된 추정부분이라 빼거나, 스터디중 확실시 되면 반영할 계획입니다.

계산 부분은 세팅값이 -1 일때는 maintenance_work_mem 값과 autovacuum_max_workers를 곱한 값을 반영하도록, 0보다 클때는 autovacuum_work_mem 값과 autovacuum_max_workers를 곱한 값을 반영하도록, 그리고 1G를 넘어설 경우에는 1G 까지만 사용한다고 하여 1G를 반영하도록 했습니다.

pg_size_pretty 함수를 사용해 깔끔하게 보이도록 했으며, 1024를 추가로 곱한 이유는 위 setting 값을 pg_size_pretty 적용했을 때 show maintenance_work_mem에서 MB 단위로 나오는것과 다르게 KB로 나와서, 단위가 한단계 낮게 나오는 것을 확인했기 때문입니다.


- 3_sharedmemory.sql
[source,sql]
----
show shared_buffers;

show wal_buffers;

select pg_size_pretty(trunc(txid_current()*2/8/8192,0)*8192 + 8192) as clog_buffers; --clog 계산식

show max_locks_per_transaction;

show max_pred_locks_per_transaction;
----
shared_buffers, wal_buffers, max_locks_per_transaction, max_pred_locks_per_transaction 세팅 값을 볼 수 있으며, transaction을 이용해 CLOG 값을 추가로 계산하여 쿼리로 볼 수 있게 반영했습니다. CLOG 값은 $PGDATA/pg_xact 경로의 0000 파일 크기와 일맥상통합니다.

- 5_dbsize.sql
[source,sql]
----
select
        datname as database_name,
        pg_size_pretty(pg_database_size(:v1)) as database_size
from
        pg_database
where
        datname = :v1
;

----

:v1 부분에서 입력받은 database명으로 그 database의 사이즈를 볼 수 있는 쿼리입니다.

- 5_tbixsize.sql
[source,sql]
----

--테이블 사이즈 및 상세 relation 사이즈 관련 쿼리
with
all_tables as
(
SELECT
        *
FROM (
SELECT
        'all_tables'::text AS table_name,
        pg_size_pretty(sum(pg_table_size(C.oid))) AS table_size,
        pg_size_pretty(sum(pg_relation_size(C.oid, 'main'))) AS relation_main_size,
        pg_size_pretty(sum(pg_relation_size(C.oid, 'fsm'))) AS relation_fsm_size,
        pg_size_pretty(sum(pg_relation_size(C.oid, 'vm'))) AS relation_vm_size,
        pg_size_pretty(sum(pg_relation_size(C.oid, 'init'))) AS relation_init_size
FROM
        pg_class C, pg_namespace N
where
        N.oid = C.relnamespace and nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r')
        --시스템 카탈로그 관련 스키마, toast 이름붙은 스키마 제외하고 select 하도록 설정
)a),
tables as
(
SELECT
        *
FROM (
SELECT
        relname AS table_name,
        pg_size_pretty(pg_table_size(C.oid)) AS table_size,
        pg_size_pretty(pg_relation_size(C.oid, 'main')) AS relation_main_size,
        pg_size_pretty(pg_relation_size(C.oid, 'fsm')) AS relation_fsm_size,
        pg_size_pretty(pg_relation_size(C.oid, 'vm')) AS relation_vm_size,
        pg_size_pretty(pg_relation_size(C.oid, 'init')) AS relation_init_size
        --relation 세부항목을 pg_relation_size에 기입하면 각 세부항목별 사이즈 볼 수 있음
FROM
        pg_class C, pg_namespace N
where
        N.oid = C.relnamespace and nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r')
)a)
SELECT
        table_name as table_name,
        table_size as table_size,
        relation_main_size as relation_main_size,
        relation_fsm_size as relation_fsm_size,
        relation_vm_size as relation_vm_size,
        relation_init_size as relation_init_size
FROM
        (SELECT * FROM all_tables UNION ALL SELECT * FROM tables) a;

--테이블의 인덱스 사이즈 관련 쿼리
with
all_tables as
(
SELECT
        *
FROM (
SELECT
        'all_tables'::text AS table_name,
        'all_indexes'::text AS index_name,
        pg_size_pretty(sum(pg_relation_size(i.indexname::TEXT))) AS index_size
        --index명을 넣으면 pg_relation_size함수로 index의 사이즈 확인 가능함
FROM
        pg_class C Left OUTER JOIN pg_indexes i on  C.relname = i.tablename,
        pg_namespace N
where
        N.oid = C.relnamespace and nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r')
)a),
tables as
(
SELECT
        *
FROM (
SELECT
        C.relname AS table_name,
        i.indexname AS index_name,
        pg_size_pretty(pg_relation_size(i.indexname::TEXT)) AS index_size
FROM
        pg_class C Left OUTER JOIN pg_indexes i on  C.relname = i.tablename,
        pg_namespace N
where
        N.oid = C.relnamespace and nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r')
)a)
SELECT
        table_name as table_name,
        index_name as index_name,
        index_size as index_size
FROM
        (SELECT * FROM all_tables UNION ALL SELECT * FROM tables) a;

--테이블사이즈 + 인덱스사이즈 합친 총 relation 사이즈 볼 수 있는 쿼리
with
all_tables as
(
SELECT
        *
FROM (
SELECT
        'all_tables'::text AS table_name,
        pg_size_pretty(sum(pg_total_relation_size(C.oid))) AS total_relation_size
FROM
        pg_class C, pg_namespace N
where
        N.oid = C.relnamespace and nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r')
)a),
tables as
(
SELECT
        *
FROM (
SELECT
        relname AS table_name,
        pg_size_pretty(pg_total_relation_size(C.oid)) AS total_relation_size
FROM
        pg_class C, pg_namespace N
where
        N.oid = C.relnamespace and nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r')
)a)
SELECT
        table_name as table_name,
        total_relation_size as total_relation_size
FROM
        (SELECT * FROM all_tables UNION ALL SELECT * FROM tables) a;

----

각 쿼리 모두 첫 행에 모든 테이블을 합친 결과값이 먼저 보이게끔 설정했습니다. 테이블 사이즈에서는 각 relation(main, fsm, vm, init) 별로 상세히 볼 수 있기에 이를 적극 반영했습니다. 인덱스 사이즈는 처음에 pg_index_size 함수를 사용했다가, 해당 테이블의 모든 인덱스를 합쳐서 보여주는 것을 확인하고, pg_relation_size 함수로 각 인덱스별 사이즈를 보여주게 끔 수정했습니다. total relation 사이즈도 마지막에 테이블 별 총 사이즈를 확인 할 수 있게 추가했습니다.

- 5_tbssize.sql
[source,sql]
----
select
        s.usename as owner,
        t.spcname as tablespace_name,
        d.datname as database_name,
        pg_tablespace_location(t.oid) as tablespace_directory, 
        -- 테이블 스페이스의 oid를 pg_tablespace_location 함수의 인자로 넣으면 경로를 표시해줌
        pg_size_pretty(pg_tablespace_size(spcname)) as tablespace_size
from
        pg_tablespace t, pg_shadow s, pg_database d
where
        t.spcowner = s.usesysid and d.dattablespace = t.oid and s.usename = :v1;
----

:v1 부분에서 입력받은 소유자 명으로 그 소유자의 tablespace 사이즈를 볼 수 있는 쿼리입니다.


- 7_diskio.sql
[source,sql]
----
/*<database hit(buffercache hit)>*/
SELECT
        'database I/O' as hit_object,
        coalesce(sum(blks_read),0) as "Database Disk Read", --read 횟수
        coalesce(sum(blks_hit),0) as "Database Cache Hit", --hit 횟수
        coalesce(round(sum(blks_hit)*100/sum(blks_hit + blks_read),2),0)||'%' as "Buffer Cache Hit Ratio",
        CASE WHEN coalesce(round(sum(blks_hit)*100/sum(blks_hit + blks_read),2),0) >= 90.00 then 'Good' -- 비율이 90이상이면
             WHEN coalesce(sum(blks_read),0) = 0 and coalesce(sum(blks_hit),0)=0 then 'Not Work' --read 횟수와 hit 횟수가 0이라면
             ELSE 'Bad' END AS "CHECK" -- 그 외는 90미만이므로 
FROM
        pg_stat_database
WHERE
        datname = :v1;

/*<table hit>*/
SELECT
        'table I/O' as hit_object,
        coalesce(sum(heap_blks_read),0) as "Table Disk Read",
        coalesce(sum(heap_blks_hit),0) as "Table Cache Hit",
        coalesce(round(sum(heap_blks_hit)*100 / sum(heap_blks_hit + heap_blks_read),2),0)||'%' as "Table Cache Hit Ratio",
        CASE WHEN coalesce(round(sum(heap_blks_hit)*100/sum(heap_blks_hit + heap_blks_read),2),0) >= 90.00 then 'Good'
             WHEN coalesce(sum(heap_blks_read),0) = 0 and coalesce(sum(heap_blks_hit),0) = 0 then 'Not Work'
             ELSE 'Bad' END AS "CHECK"
FROM
        pg_statio_user_tables;

/*<index hit>*/
SELECT
        'index I/O' as hit_object,
        coalesce(sum(idx_blks_read),0) as "Idx Disk Read",
        coalesce(sum(idx_blks_hit),0)  as "Idx Cache Hit",
        coalesce(round(sum(idx_blks_hit)*100/ sum(idx_blks_hit + idx_blks_read),2),0)||'%' as "Idx Hit Ratio",
        CASE WHEN coalesce(round(sum(idx_blks_hit)*100/sum(idx_blks_hit + idx_blks_read),2),0) >= 90.00 then 'Good'
             WHEN coalesce(sum(idx_blks_read),0) = 0 and coalesce(sum(idx_blks_hit),0) = 0 then 'Not Work'
             ELSE 'Bad' END AS "CHECK"
FROM
        pg_statio_user_indexes;

/*<sequence hit>*/
SELECT
        'sequence I/O' as hit_object,
        coalesce(sum(blks_read),0) as "Sequence Disk Read",
        coalesce(sum(blks_hit),0) as "Sequence Cache Hit",
        coalesce(round(sum(blks_hit)*100/sum(blks_hit + blks_read),2),0)||'%' as "Sequence Hit Ratio",
        CASE WHEN coalesce(round(sum(blks_hit)*100/sum(blks_hit + blks_read),2),0) >= 90.00 then 'Good'
             WHEN coalesce(sum(blks_read),0) = 0 and coalesce(sum(blks_hit),0)=0 then 'Not Work'
             ELSE 'Bad' END AS "CHECK"
FROM
        pg_statio_user_sequences;

/*<slru(simple least-recently-used)>*/
SELECT
        'slru I/O' as hit_object,
        coalesce(sum(blks_read),0) as "SLRU Disk Read",
        coalesce(sum(blks_hit),0) as "SLRU Cache Hit",
        coalesce(round(sum(blks_hit)*100/sum(blks_hit + blks_read),2),0)||'%' as "SLRU Hit Ratio",
        CASE WHEN coalesce(round(sum(blks_hit)*100/sum(blks_hit + blks_read),2),0) >= 90.00 then 'Good'
             WHEN coalesce(sum(blks_read),0) = 0 and coalesce(sum(blks_hit),0)=0 then 'Not Work'
             ELSE 'Bad' END AS "CHECK"
FROM
        pg_stat_slru;

----

모든 I/O 항목 공통으로 read 횟수와 hit 횟수를 통해 hit 비율을 따져서 hit ratio를 계산합니다. 데이터베이스 별로 볼 수 있도록 pg_statio_user_% 카탈로그를 사용했고, slru는 데이터베이스 상관없이 공통으로 볼 수 있습니다.

- 8_sessioncheck.sql
[source,sql]
----
/* session check */
select
        pid as process_id,
        usename as owner,
        datname as dbname,
        application_name as application_name,
        client_addr || ':' || client_port as ip_port_info, --ip와 port정보를 한꺼번에 볼 수 있도록
        to_char(backend_start, 'YYYY-MM-DD HH24:MI:SS') as session_started_time, 
        -- 마이크로초까지 나오는 시간을 보기좋게 초까지만 잘라서 문자로 변환
        to_char(state_change, 'YYYY-MM-DD HH24:MI:SS') as session_changed_time,
        state as current_status,
        --substr(query,1,100) as query, 쿼리 내용까지 보기엔 길어서 주석처리, 다만 query id는 추가해야함
        wait_event_type as wait_type, -- wait_event_type에 유형이 있음. 별도 정리
        wait_event as wait, -- wait_event에도 유형이 있음. 별도 정리
        backend_type --backend_type에도 유형이 있음. 별도 정리
from
        pg_stat_activity;

----

pg_stat_activity를 이용해 현재 세션에 관련된 정보를 볼 수 있습니다. query id만 볼 수 있도록 수정할 예정이며, wait_event_type, wait_event, backend_type에서 나타나는 유형은 별도로 정리합니다.


- 8_transactionchk.sql
[source,sql]
----
/*transaction check*/
select
        pid as process_id,
        usename as owner,
        datname as dbname,
        to_char(xact_start, 'YYYY-MM-DD HH24:MI:SS') as tx_started_time,
        to_char(state_change, 'YYYY-MM-DD HH24:MI:SS') as tx_changed_time,
        state as current_status,
        wait_event_type as waiting_type,
        wait_event as wait_event,
        substr(query,1,100) as query
from
        pg_stat_activity
where
        xact_start is not null;
----
마찬가지로 pg_stat_activity를 이용해 현재 트랜젝션 관련된 정보를 볼 수 있습니다. 마찬가지로 query id만 볼 수 있도록 수정할 예정이며, 항목이 한눈에 들어오기 힘들 수 있어서 여러번 나누어서 보여주도록 수정하는 것도 괜찮을 것 같습니다.

- 9_sqlplan.sql

explain verbose가 가능한 쿼리만 뽑아내서 query plan을 직접 실행할 수 있도록 별도 sql 파일 생성해서 실행하도록 하려 했으나, select 이외 구문을 실행할 경우 위험하기 때문에 우선 이 과정을 삭제하고 공백으로 놔뒀습니다. 이쪽에는 plan 정보를 볼 수 있는 시스템 카탈로그를 찾아서 그 정보를 쿼리로 볼 수 있도록 수정할 예정입니다.


- 9_topsqlchk.sql
[source,sql]
----
/* total top 10 query */

select
        a.userid,
        b.usename,
        a.dbid,
        c.datname,
        a.queryid,
        substr(a.query, 1, 100) as query, -- substr - 문자열 자르는 함수
        a.calls, -- statement가 콜된 횟수
        a.total_exec_time,
        a.min_exec_time,
        a.max_exec_time,
        a.rows
from
        public.pg_stat_statements a
join pg_catalog.pg_user b on a.userid = b.usesysid
join pg_catalog.pg_stat_database c on a.dbid = c.datid
where
        c.datname = :v1
order by a.max_exec_time desc
limit 10;
----

이부분도 query를 직접 보여주는 부분은 자르고 query id만 표시되게끔 수정할 예정이며 min_exec_time과 max_exec_time을 이용해 평균 실행시간을 추가하면서 또 필요한 부분도 추가하여 보기 좋게 쿼리 결과를 나눠서 보여주도록 할 예정입니다. pg_stat_statements는 쿼리 및 실행시간, 콜 된 횟수등 자세한 내용이 담긴 extension으로, 이 extension은 추후 기술지원 시에 필요할 것이라 생각합니다. pg_stat_statements는 과거부터 현재까지 실행된 쿼리 정보를 담고있어서 예전에 오래 실행되었던 쿼리도 찾을 수 있는데, 이와 별도로 pg_stat_activity와 연계해서 현재 상태의 top 10 query도 추가로 뽑아 낼 수 있을 지 고민하고 있습니다.

- 10_tableusage.sql
[source,sql]
----
SELECT
       relname AS "table_name",
       pg_size_pretty(pg_table_size(C.oid)) AS "table_size"
FROM
       pg_class C
LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
WHERE
        nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r')
ORDER BY pg_table_size(C.oid)
DESC;
----

시스템 카탈로그 담고있는 스키마 제외 단순 테이블 사이즈만 보여주는 쿼리 입니다.

- 10_tuplestate.sql
[source,sql]
----
SELECT
        c.relname AS table_name,
        pg_stat_get_live_tuples(c.oid) + pg_stat_get_dead_tuples(c.oid) as total_tuple,
        pg_stat_get_live_tuples(c.oid) AS live_tuple,
        pg_stat_get_dead_tuples(c.oid) AS dead_tupple,
        CASE WHEN pg_stat_get_live_tuples(c.oid) = 0 and pg_stat_get_dead_tuples(c.oid)=0 then 0
        ELSE round(100*pg_stat_get_live_tuples(c.oid) / (pg_stat_get_live_tuples(c.oid) + pg_stat_get_dead_tuples(c.oid)),2)
        END ||'%' as live_tuple_rate
/*      CASE WHEN pg_stat_get_live_tuples(c.oid) = 0 and pg_stat_get_dead_tuples(c.oid)=0 then 0
        ELSE round(100*pg_stat_get_dead_tuples(c.oid) / (pg_stat_get_live_tuples(c.oid) + pg_stat_get_dead_tuples(c.oid)),2)
        END ||'%' as dead_tuple_rate*/
FROM
        pg_class AS c, pg_stat_user_tables AS u, pg_namespace AS n
WHERE
        n.oid = c.relnamespace AND c.relname = u.relname
ORDER BY dead_tupple DESC;
----
pg_stat_get_live_tuples 함수와 pg_stat_get_dead_tuples 함수를 이용해 총 tuple수와 live tuple과 dead tuple 갯수를 볼 수 있고, 이를 이용해 live tuple의 비율도 계산 해서 볼 수 있습니다. dead tuple은 live tuple 비율만 계산되면 저절로 알 수 있기에 주석처리 했습니다.

- 10_vacuumcheck.sql
[source,sql]
----
/* vacuum used - vacuum verbose 'tablename'*/
select
        relname,
        last_vacuum, -- 마지막 vacuum이 돌았던 시간
        last_autovacuum, -- 마지막 autovacuum이 돌았던 시간
        vacuum_count, -- vacuum이 돈 횟수
        autovacuum_count -- autovacuum이 돈 횟수
from
        pg_stat_user_tables
order by last_vacuum, last_autovacuum;


/* vacuum analyze command used - vacuum analyze 'tablename'*/
select
        relname,
        last_analyze, -- 마지막 analyze가 돌았던 시간
        last_autoanalyze, -- 마지막 autoanalyze가 돌았던 시간
        analyze_count, -- analyze가 돈 횟수
        autoanalyze_count -- autoanalyze가 돈 횟수
from
        pg_stat_user_tables
order by last_analyze, last_autoanalyze;
----

pg_stat_user_tables(전체는 pg_stat_all_tables) 컬럼에는ㄴ vacuum과 analyze를 각각 볼 수 있기에 이를 vacuum 따로 analyze 따로 볼 수 있도록 나눠놨습니다.

- 10_vacuumstate.sql
[source,sql]
----
select
        *
from
        pg_stat_progress_vacuum;
----

실시간으로 vacuum이 돌 때 상태를 볼 수 있는 sql입니다. pg_stat_progress_vacuum의 컬럼 내용도 많지 않고 모두 볼만한 내용이라 생각하여 *로 처리했습니다.

- 12_check_lock.sql
[source,sql]
----
SELECT
        t.relname,
        l.locktype, -- lock 개체 유형, 별도 정리
        page,
        virtualtransaction, -- lock을 보유하거나 대기 중인 트랜잭션의 가상 ID
        pid, -- 이 lock을 보유하거나 기다리는 서버 프로세스의 id
        mode, -- 이 프로세스에서 보유하거나 원하는 lock 유형
        granted
FROM
        pg_locks l, pg_stat_all_tables t
WHERE
        l.relation = t.relid
ORDER BY relation ASC;


/* lock query modified*/

SELECT
        blocked_locks.pid     AS blocked_pid,
        blocked_activity.usename  AS blocked_user,
        blocking_locks.pid     AS blocking_pid,
        blocking_activity.usename AS blocking_user,
        blocked_activity.query    AS blocked_statement,
        blocking_activity.query   AS current_statement_in_blocking_process
FROM
        pg_catalog.pg_locks         blocked_locks
JOIN pg_catalog.pg_stat_activity blocked_activity  ON blocked_activity.pid = blocked_locks.pid
JOIN pg_catalog.pg_locks         blocking_locks
        ON blocking_locks.locktype = blocked_locks.locktype
        AND blocking_locks.database IS NOT DISTINCT FROM blocked_locks.database
        AND blocking_locks.relation IS NOT DISTINCT FROM blocked_locks.relation
        AND blocking_locks.page IS NOT DISTINCT FROM blocked_locks.page
        AND blocking_locks.tuple IS NOT DISTINCT FROM blocked_locks.tuple
        AND blocking_locks.virtualxid IS NOT DISTINCT FROM blocked_locks.virtualxid
        AND blocking_locks.transactionid IS NOT DISTINCT FROM blocked_locks.transactionid
        AND blocking_locks.classid IS NOT DISTINCT FROM blocked_locks.classid
        AND blocking_locks.objid IS NOT DISTINCT FROM blocked_locks.objid
        AND blocking_locks.objsubid IS NOT DISTINCT FROM blocked_locks.objsubid
        AND blocking_locks.pid != blocked_locks.pid

JOIN pg_catalog.pg_stat_activity blocking_activity ON blocking_activity.pid = blocking_locks.pid
WHERE NOT blocked_locks.granted;
----
첫번째 쿼리는 pg_locks와 pg_stat_all_tables를 이용해 모든 락을 볼 수 있도록 정리한 쿼리입니다. 더 필요한 내용이 있으면 pg_locks 테이블 참조하여 추가했으면 합니다.

두번째 쿼리는 실제 락이 발생했을 경우 lock 현황을 볼 수 있는 쿼리입니다. 커뮤니티에서 정리된 쿼리를 가져왔는데, IS NOT DISTINCT FROM을 이용해 pg_locks와 pg_stat_activity를 이용해 bloking, blocked를 구분해서 보여줍니다. row-level locks 만 찾을 수 있는 쿼리라고 합니다. lock 부분도 스터디를 통해 내용 보완이 필요합니다. +
출처 - https://wiki.postgresql.org/wiki/Lock_Monitoring



== 4. WAIT_EVENT_TYPE, WAIT_EVENT, BACKEND_TYPE 유형 정리

== 5. pg_locks에서의 locktype과 mode 유형 정리